### ISSUE TITLE
Make the certification pack valid for both Symfony 2 and Symfony 3

### ISSUE THREAD

**Issue by mickaelandrieu** [certificationy/symfony-pack#51]
- [ ] Removed all questions that can have differents answers in Symfony2/Symfony3
- [ ] Add specific questions about Symfony3 (including new components)

**Comment by timonf** [comment]
Maybe you could think about the yaml format. Would be great to have something like:

```yaml
questions:
    -
        question: 'Which of these response objects does not exists?'
        versions: ['symfony2', 'symfony3', 'symfony4']
        answers:
            - {value: XmlResponse,        correct: true}
            - {value: JsonResponse,       correct: false}
            - {value: BinaryFileResponse, correct: false}
            - {value: RedirectResponse,   correct: false}
```
